[build.environment]
  NPM_VERSION = "6.13.4"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[dev]
  command = "npm run start"
  targetPort = 8888
