backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "site/static/uploads"  # Where media files will be stored in the repo
public_folder: "/uploads"            # The 'src' attribute for uploaded media will begin with this value

collections:
  - name: "blog"                 # Used in routes, e.g., /admin/collections/blog
    label: "Blog"                # Used in the UI
    folder: "site/content/blog"  # The path to the folder where the documents are stored
    create: true                 # Allow users to create new documents in this collection
    slug: "{{slug}}"             # Filename template, e.g., YYYY-MM-DD-title.md
    fields:                      # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
